# Generated by Django 6.0.3 on 2026-04-25 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_mlx_profile_id_user_ml_folder_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertaskmanager',
            name='error_message',
        ),
        migrations.AlterField(
            model_name='usertaskmanager',
            name='started_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
