# Generated by Django 6.0.3 on 2026-04-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_usertaskmanager_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskmanager',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
