# Generated by Django 6.0.3 on 2026-04-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usertaskmanager_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertaskmanager',
            old_name='details',
            new_name='comment',
        ),
    ]
