# Generated by Django 6.0.3 on 2026-04-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_details_usertaskmanager_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskmanager',
            name='company_queries',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='usertaskmanager',
            name='company_queries_count_from',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='usertaskmanager',
            name='company_queries_count_to',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='usertaskmanager',
            name='interactions_count_from',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='usertaskmanager',
            name='interactions_count_to',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='usertaskmanager',
            name='limit_on_reviews_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertaskmanager',
            name='pause_multiplier',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AddField(
            model_name='usertaskmanager',
            name='prompt_parameters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usertaskmanager',
            name='prompts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='usertaskmanager',
            name='restricted_company_queries',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='usertaskmanager',
            name='review_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertaskmanager',
            name='target_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
