# Generated by Django 6.0.3 on 2026-04-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usertaskmanager_company_queries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ml_folder_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ml_profile_id',
        ),
        migrations.AddField(
            model_name='usertaskmanager',
            name='ml_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usertaskmanager',
            name='ml_profile_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
