# Generated by Django 6.0.3 on 2026-04-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_ml_folder_id_remove_user_ml_profile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='asdf345DF43$S#!d', max_length=255),
            preserve_default=False,
        ),
    ]
