# Generated by Django 6.0.3 on 2026-04-29 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertaskmanager',
            options={'ordering': ['-execute_at'], 'verbose_name': 'User task', 'verbose_name_plural': 'User tasks'},
        ),
        migrations.RenameField(
            model_name='usertaskmanager',
            old_name='created_at',
            new_name='execute_at',
        ),
    ]
