# Generated by Django 6.0.3 on 2026-05-01 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_usertaskmanager_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertaskmanager',
            old_name='status',
            new_name='task_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='usertaskmanager',
            name='ml_folder_id',
        ),
        migrations.RemoveField(
            model_name='usertaskmanager',
            name='ml_profile_id',
        ),
        migrations.RemoveField(
            model_name='usertaskmanager',
            name='user',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=255)),
                ('profile_status', models.CharField(choices=[('new', 'New'), ('warming', 'Warming'), ('ready', 'Ready')], default='new', max_length=20)),
                ('ml_profile_id', models.CharField(max_length=255)),
                ('ml_folder_id', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='user.user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.AddField(
            model_name='usertaskmanager',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user.profile'),
        ),
    ]
