# Generated by Django 6.0.3 on 2026-05-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_status_usertaskmanager_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskmanager',
            name='interactions_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usertaskmanager',
            name='reviews_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('warming', 'Warming'), ('ready', 'Ready')], default='new', max_length=20, null=True),
        ),
    ]
