# Generated by Django 6.0.3 on 2026-05-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_profile_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskmanager',
            name='maximum_longer_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertaskmanager',
            name='maximum_review_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
