# Generated by Django 6.0.3 on 2026-05-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_usertaskmanager_maximum_longer_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskmanager',
            name='task_status',
            field=models.CharField(choices=[('on_hold', 'On hold'), ('pending', 'Pending'), ('in_progress', 'In progress'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
