# Generated by Django 6.0.3 on 2026-05-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_usertaskmanager_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertasklog',
            name='level',
            field=models.CharField(choices=[('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR'), ('debug', 'DEBUG')], default='info', max_length=20),
        ),
    ]
