# Generated by Django 6.0.3 on 2026-05-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_profile_email_profile_fa2_secret_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_status',
            field=models.CharField(blank=True, choices=[('failed', 'Failed'), ('new', 'New'), ('warming', 'Warming'), ('ready', 'Ready')], default='new', max_length=20, null=True),
        ),
    ]
