# Generated by Django 6.0.3 on 2026-05-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_profile_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertasklog',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
