# Generated by Django 6.0.3 on 2026-05-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_usertasklog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskmanager',
            name='interactions_count_from',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usertaskmanager',
            name='interactions_count_to',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
