# Generated by Django 6.0.3 on 2026-05-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_usertaskmanager_interactions_count_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertaskmanager',
            name='interactions_count',
        ),
        migrations.RemoveField(
            model_name='usertaskmanager',
            name='reviews_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='interactions_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviews_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='warmup_stage',
            field=models.CharField(blank=True, choices=[('day_1_2', 'Day 1-2'), ('day_3_4', 'Day 3-4'), ('day_5_6', 'Day 5-6'), ('day_7_9', 'Day 7-9'), ('day_10_14', 'Day 10-14'), ('day_14_21', 'Day 14-21')], default='day_1_2', max_length=20, null=True),
        ),
    ]
