# Generated by Django 6.0.3 on 2026-05-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_usertaskmanager_interactions_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskmanager',
            name='interactions_cout',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
