# Generated by Django 6.0.3 on 2026-05-11 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_usertaskmanager_interactions_cout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertaskmanager',
            old_name='interactions_cout',
            new_name='interactions_count',
        ),
    ]
