# Generated by Django 6.0.3 on 2026-05-14 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_rename_interactions_cout_usertaskmanager_interactions_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='warmup_stage',
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_day',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_completed_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stage_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('in_progress', 'In progress'), ('success', 'Success'), ('failed', 'Failed'), ('retry_required', 'Retry required'), ('paused', 'Paused'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_failed_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_successful_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='ProfileDayProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('scenario_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('retry_required', 'Retry required')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('interactions_count', models.IntegerField(blank=True, default=0, null=True)),
                ('reviews_count', models.IntegerField(blank=True, default=0, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_progress', to='user.profile')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_progress', to='user.usertaskmanager')),
            ],
            options={
                'verbose_name': 'Profile day progress',
                'verbose_name_plural': 'Profile day progress',
                'indexes': [models.Index(fields=['profile', 'day_number'], name='user_profil_profile_aec36c_idx'), models.Index(fields=['status'], name='user_profil_status_19c635_idx'), models.Index(fields=['scenario_name'], name='user_profil_scenari_a24cb8_idx')],
            },
        ),
    ]
