# Generated by Django 6.0.3 on 2026-05-19 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_remove_profile_profile_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('review_title', models.CharField(blank=True, max_length=500, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review_link', models.URLField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='user.profile')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='user.usertaskmanager')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewStatisticsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Reviews Statistics',
                'verbose_name_plural': 'Reviews Statistics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.review',),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['profile'], name='user_review_profile_30ba7e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['company'], name='user_review_company_a8e438_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='user_review_created_8ca169_idx'),
        ),
    ]
