# Generated by Django 6.0.3 on 2026-05-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(blank=True, choices=[('successful', 'Successful'), ('unsuccessful', 'Unsuccessful')], default=None, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status'], name='user_review_status_081dfb_idx'),
        ),
    ]
