# Generated by Django 6.0.3 on 2026-05-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_review_created_at_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='trustpilot_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
